addReviewers: true
addAssignees: false
numberOfReviewers: 0
useReviewGroups: true
reviewGroups:
  groupA:
    - anna-giang
    - katherinemof
    - nchong128
filterLabels:
  include:
    - netlify-cms/draft
    - netlify-cms/pending_review
    - netlify-cms/pending_publish
